version: '3'
services:
  website:
    container_name: php_crud
    image: php_crud_img
    networks:
      - frontend
    build:
      context: ./
    volumes:
      - /Users/olegvpc/PHP/php-crud-docker/src:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
        - '8080:80'
    restart: always
    networks:
      - frontend
    environment:
        - PMA_HOST=host.docker.internal
        - PMA_ARBITRARY=1
    depends_on:
        - mysql

  mysql:
    image: mysql:latest
    networks:
      - backend
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_DATABASE: mysql

    ports:
      - "3306:3306"
networks:
  frontend:
  backend: